package com.swlc.snake.main;

import com.swlc.snake.util.Grid;
import com.swlc.snake.view.Ground;
import com.swlc.snake.view.ScoreBoard;
import com.swlc.snake.view.Snake;
import com.swlc.snake.constant.Route;
import com.swlc.snake.handler.SnakeHandler;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;


/**
 * @author Chanuka Sandaruwan
 * @created 01/08/2021 - 10:51 pm
 * @project swlc-snake-game
 */

public class Main extends JFrame {

    private ScoreBoard scoreBoard;
    private Ground gameField;
    private Thread thread;
    private Snake snake;

    // Current path of the snake
    private Route direction = Route.UP;

    private boolean started = false;


    public Main() {
        initComponents();
        initGame();
        initFrame();
    }

    private void initComponents() {
        setLayout(new GridBagLayout());
        addKeyListener(new KeyboardHandler());

        gameField = new Ground();
        add(gameField, new Grid(0, 1, 8, 8));

        scoreBoard = new ScoreBoard();
        add(scoreBoard, new Grid(0, 0, 8, 1));

    }

    private void initGame() {
        snake = new Snake(gameField, scoreBoard);
        Runnable r = new SnakeHandler(gameField, snake, this);
        thread = new Thread(r);
    }

    private void initFrame() {
        pack();
        setTitle("SWLC Snake Game");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setVisible(true);

        JOptionPane.showMessageDialog(null, "Use the up arrow key to start the game.", "Info message", JOptionPane.INFORMATION_MESSAGE);
    }


    /**
     *  Starts a new game
     */
    public void newGame() {
        started = true;
        thread.start();
    }


    /**
     * Ends the game and show the score to user and enables the user to decide whether he wants to continue to play by displaying a dialog box.
     */
    public void gameOver() {

        int returnValue = JOptionPane.showConfirmDialog(this, "Your score: " + scoreBoard.getScore() + "\n Do you want to start a new game?", "GAME OVER!",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        switch (returnValue) {
            case JOptionPane.OK_OPTION:
                direction = Route.UP;
                started = false;
                snake = new Snake(gameField, scoreBoard);
                scoreBoard.clear();
                gameField.initDefaults();
                scoreBoard.repaint();
                gameField.repaint();
                Runnable r = new SnakeHandler(gameField, snake, this);
                thread = null;
                thread = new Thread(r);
                break;

            case JOptionPane.CANCEL_OPTION:
                System.exit(0);
                break;
            default:
                JOptionPane.showMessageDialog(getParent(), "Sorry :( Something went wrong \n Please relaunch the game");
                break;
        }
    }


    /**
     * First start point of the game
     */
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main();
            }
        });
    }

    /**
     *  Acts as a KeyListener and responds to the events generated by one of the 4 arrow keys, whenever they are pressed.
     */
    private class KeyboardHandler extends KeyAdapter {

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_UP) {
                if (direction == Route.DOWN)
                    return;
                if (!started)
                    newGame();
                if (snake != null) {
                    snake.changeDirection(Route.UP);
                    direction = Route.UP;
                }
            }

            if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                if (direction == Route.UP)
                    return;
                if (!started)
                    newGame();
                if (snake != null) {
                    snake.changeDirection(Route.DOWN);
                    direction = Route.DOWN;
                }
            }

            if (e.getKeyCode() == KeyEvent.VK_LEFT) {
                if (direction == Route.RIGHT)
                    return;
                if (!started)
                    newGame();
                if (snake != null) {
                    snake.changeDirection(Route.LEFT);
                    direction = Route.LEFT;
                }
            }

            if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                if (direction == Route.LEFT)
                    return;
                if (!started)
                    newGame();
                if (snake != null) {
                    snake.changeDirection(Route.RIGHT);
                    direction = Route.RIGHT;
                }
            }
        }
    }
}
